[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-v --ff"
testpaths = [
    "tests",
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
src_paths = [".", "tests"]
py_version = 311
line_length = 88


[tool.mypy]
show_error_context = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
check_untyped_defs = true
disallow_incomplete_defs = true
python_version = "3.11"

[tool.ruff]
src = ["."]

line-length = 88
lint.select = [
    "C901",
    "C",
    "Q",
    "A",
    "N",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # annotations
    #        "ANN",
]
lint.ignore = [
    "ANN101", # missing-type-self
]
lint.fixable = ["ALL"]
lint.unfixable = []
exclude = [
    ".git",
    ".idea",
    ".mypy_cache",
    ".tox",
    ".venv"
]
target-version = "py310"

[tool.ruff.lint.mccabe]
# Flake8 is 15 - which I feel is too high
max-complexity = 8
