name: code-checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:

  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: pip3 install flake8 mypy isort black ruff
      - name: Run flake8
        run: python3 -m flake8  --show-source --count --statistics kafkian/ tests/
      - name: Run mypy
        run: mypy kafkian/
        continue-on-error: true
      - name: Run black check
        run: black --check kafkian/ tests/
      - name: Run isort check
        run: isort --check  kafkian/ tests/
      - name: Run ruff
        run: ruff check --output-format=github .
        continue-on-error: true

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        confluent-kafka-python-version: [ "2.6.0", "2.7.0", "2.8.0" ]
        fastavro-version: [ "1.9.7", "1.10.0" ]
        pydantic-version: [ "2.8.0", "2.10.6" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install requirements
        run: pip3 install -r requirements.dev.txt
      - name: install dependencies
        run: pip3 install confluent-kafka[avro]==${{ matrix.confluent-kafka-python-version }} fastavro==${{ matrix.fastavro-version }} pydantic==${{ matrix.pydantic-version }}
      - name: Run unit-tests
        run: make unittest
